name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Run Python script and save output to file
        run: python v2ray_server_finder.py

      - name: Commit and push files
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "Github Actions"
          author_email: "actions@github.com"
          message: "Updated 🥳"
          add: "."
          push: "https://github.com/firozsoft/internet.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
