name: Update Configs
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the collector script
        run: python collector_async.py

      - name: Run the pinger script
        run: python pinger.py

      - name: Push updated file
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "Github Actions"
          author_email: "actions@github.com"
          message: "Updated 🥳"
          add: "."
          push: "https://github.com/firozsoft/internet.git"